### ISSUE TITLE
Should use jvm11 in 2019.

### ISSUE THREAD

**Issue by madper** [Jason5Lee/primes_benchmark#2]
It's 2019 now. And jvm12 will be released in a couple of weeks. There is no reason to do the benchmark with jvm8...

you will get similar result if you:
1. use u32
2. use jvm8
![screenshot from 2019-03-02 12-44-02](https://user-images.githubusercontent.com/451815/53677324-f0b53f00-3ce8-11e9-9203-f15ae44eec8d.png)

**Comment by Jason5Lee** [comment]
JDK8 is the minimal requirement, you can use any JDK that is compatible.
